[package]
name = "cardiag"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Application de diagnostic automobile"

[lib]
name = "cardiag_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
diagnostic-core = { path = "../crates/diagnostic-core" }

[dev-dependencies]
serde_json.workspace = true
